CREATE TABLE agentes_saude (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    telefone varchar(15) not null,
    numero_registro varchar(8) not null,
    unidade_saude varchar(255) not null
);

CREATE TABLE pacientes (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    telefone varchar(15) not null,
    email varchar(255)
);

CREATE TABLE visitas (
    id bigint generated by default as identity primary key,
    id_agente_saude bigint not null,
    id_paciente bigint not null,
    data_visita TIMESTAMP not null,
    motivo varchar(255),
    observacoes varchar(255),
    status varchar(50) default 'PENDENTE',
    fin_latitude DECIMAL(10, 8),
    fin_longitude DECIMAL(11, 8)
    constraint fk_id_agente_saude foreign key (id_agente_saude) references agentes_saude(id),
    constraint fk_id_paciente foreign key (id_paciente) references pacientes(id)
);